### ISSUE TITLE
Plotting coastlines

### ISSUE THREAD

**Issue by aozbakir** [paudetseis/PlateCurie#1]
Hi Pascal,

I try to plot coastlines along with project results. But I am getting problems.

I followed plateflex examples, where contours are extracted from within topo class:

xmint,` xmaxt, ymint, ymaxt, zmint, zmaxt, dxt, dyt, nxt, nyt = \
pd.read_csv('~/Documents/WORK/CPD/Data/topo_TUR.xyz', sep='\t', nrows=0).columns[1:].values.astype(float)
nxt = int(nxt); nyt = int(nyt)

topodata = pd.read_csv('~/Documents/WORK/CPD/Data/topo_TUR.xyz', sep='\t', \
    skiprows=1, names=['x', 'y', 'z'])['z'].values.reshape(nyt,nxt)[::-1]
topo = TopoGrid(topodata, dxt, dyt)
contours = topo.make_contours(0.)

Plotting works fine. But when I use project.plot_results with contours=contours flag, for example: 
project.plot_results(mean_A=True, mask=True, contours=contours, cmap='Spectral')

I get AttributeError: 'Project' object has no attribute 'nn'

contours is a list object, I suppose this makes the problem. But I don't know how to solve it. Could you provide some hints?

Thanks in advance,
Ali

**Comment by paudetseis** [comment]
Dear Ali,
The error arises because the method `plot_results` uses the `Project` object attribute `nn` to plot the contours (lines 799-800 of the module `classes.py`). The object obtains the attribute `nn` when the method `estimate_grid` is run (see line 498 of the module `classes.py`). Your error message would mean that the method `estimate_grid` has not yet been run on `project`, and therefore the attribute `nn` is not yet stored in `project`. When you run `plot_results`, you therefore get the AttributeError that `Project` has not attribute `nn`. 

Solution: run `estimate_grid` on `project` first, then use `plot_results`.

I hope this helps
Pascal

**Comment by aozbakir** [comment]
Hi Pascal,

In fact, after reading and initializing the magnetic anomaly grid and then the topography grids I ran estimate_grid() on the project:
project = Project(grids=[mag]) # Tried Project(grids=[mag, topo])] too

project.init()
project.estimate_grid(10) # project.nn gives 10

project.plot_results(mean_dz=True, contours=contours, mask=True, cmap='Spectral')

/home/aozb/.conda/envs/pflex/lib/python3.7/site-packages/platecurie/classes.py:800: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  contours = np.array(contours)/self.nn

I tried ct=np.array(contours)/project.nn and used contours=ct, then there are no error messages but no contours either.

Do you think it is because estimate_grid() does not decimate topography contours?

Best,
Ali

**Comment by paudetseis** [comment]
Hi Ali,

This sounds like a different problem. Can you post a minimal script that reproduces this behaviour? Also, please post the result of `conda list`. It sounds like numpy has changed how ndarrays are created, which will require a change in the code.

Do you also get the same error message in `PlateFlex`?

Thanks
Pascal

**Comment by aozbakir** [comment]
```python
import numpy as np
import pandas as pd
from platecurie import MagGrid, Project
from plateflex import TopoGrid

xmin, xmax, ymin, ymax, zmin, zmax, dx, dy, nx, ny = \
pd.read_csv('mag_TUR.xyz', sep='\t', nrows=0).columns[1:].values.astype(float)
nx = int(nx); ny = int(ny)
magdata = pd.read_csv('mag_TUR.xyz', sep='\t', \
    skiprows=1, names=['x', 'y', 'z'])['z'].values.reshape(ny,nx)[::-1]
magdata[magdata<-750] = np.nan
magdata[magdata>1000] = np.nan
mag = MagGrid(magdata, dx, dy)
mask = (magdata==0)

xmint, xmaxt, ymint, ymaxt, zmint, zmaxt, dxt, dyt, nxt, nyt = \
pd.read_csv('topo_TUR.xyz', sep='\t', nrows=0).columns[1:].values.astype(float)
nxt = int(nxt); nyt = int(nyt)
topodata = pd.read_csv('topo_TUR.xyz', sep='\t', \
    skiprows=1, names=['x', 'y', 'z'])['z'].values.reshape(nyt,nxt)[::-1]
topo = TopoGrid(topodata, dx, dy)
contours = topo.make_contours(level=0.0)

project = Project(grids=[mag, topo])
project.init()
project.mask = mask
project.estimate_grid(1)

project.mean_dz_grid = project.mean_dz_grid + project.mean_zt_grid
contours = topo.make_contours(level=0.0)
project.plot_results(mean_dz=True, contours=ct, mask=True, cmap='Spectral')
```

mag_TUR.xyz and topo_TUR.xyz are pixel registered grids generated  from EMAG2v3 and ETOPO1 data respectively with same sampling intervals:
`grdproject EMAG2_V3_20170530.grd -R20/50/30/50 -JM10c -Gmag_TUR.grd -D20 -Fk`
and
`grdproject ETOPO1_Ice_g_gmt4.grd -R20/50/30/50 -JM10c -Gtopo_TUR.grd -r -D20 -Fk`

`PlateFlex` works just fine.  In fact, I can plot the contours on the magnetic anomaly map with 
`mag.plot(mask=mask, contours=contours, vmin=-300, vmax=300, cmap='Spectral')
`

(fig: example.png)
![example](https://user-images.githubusercontent.com/16939794/96289667-1f7f4680-0fee-11eb-8b94-c91b4f1f0e00.png)
But of course these plotting routines are different from `project.plot_results()`

You can find the list of packages of pflex env attached in conda_list.txt
[conda_list.txt](https://github.com/paudetseis/PlateCurie/files/5393252/conda_list.txt)

Hope these information can help.

Best,
Ali

EDIT 1:
I verified that the following line works and gives correct plot. But, when I estimate model parameters at every N points, the topo=0 contours don't get decimated accordingly. So the following only works for `project.estimate_grid(1)`

```python
from plateflex.plotting import plot_real_grid as plt2
plt2(project.mean_dz_grid, title='mean dz', cmap='Spectral', contours=contours)
```

EDIT 2:
I found a work around solution:
The following excerpt makes the contours scaled correctly.
```python
from plateflex.plotting import plot_real_grid as plt2

contours = topo.make_contours(level=0.0)
contours=np.array(contours)/project.nn
plt2(project.mean_dz_grid, title='mean dz', cmap='Spectral', contours=contours)
```
![test](https://user-images.githubusercontent.com/16939794/96457487-82f4b880-1228-11eb-8ab1-320f8e0e1cf6.png)

but the coastlines are not truncated for  cell numbers that are not integer multiples.

**Comment by paudetseis** [comment]
Dear Ali,

You had the right idea to plot the map using the PlateFlex function `plot_real_grid` since this is the function called in `plot_results`. There was a problem with `plot_results` where the contours were actually not used in the call to `plot_real_grid`, so the contours were never plotted. I have fixed the master branch on GitHub. If you cloned or forked the repository, make sure to fetch the latest version and merge those changes (`git pull`), and then re-installing using `pip install .`

And you are correct that the coastlines are not truncated for cell numbers that are not integer multiples, but the grid cells should be mapped to their correct location.

Thanks for your input that led to an improvement in PlateCurie!

**Comment by aozbakir** [comment]
Dear Pascal,

The issue is resolved after installing the newest version. I am very happy to be involved in an improvement.

Best
